### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by halbielee** [Lixy1997/Group-WSSS#1]
Hello, 

Thank you for sharing the code for the excellent job. 

I have troubles when running your code. 

1. There is no "res.py"  in "run/pascal".  There is only "vis.py" which is not the training code.

2. By utilizing "train.py", I might be possible to execute the training code, but there are several bugs.
- The reference is wrong. 
https://github.com/Lixy1997/Group-WSSS/blob/5c1fc2cdf4bd3f2ecde6603844e5c9deddeb4dc3/train.py#L18
I think this should be `from utils.avgMeter import AverageMeter`

-  another reference issue
- https://github.com/Lixy1997/Group-WSSS/blob/5c1fc2cdf4bd3f2ecde6603844e5c9deddeb4dc3/train.py#L60
I think `gnn` should be `vgg_gnn`

3, Files for `args.train_list` and `args.test_list` are not provided. 
These file lists seem to have file name and zero-one vector which has class information
ex) 'name 0 0 0 1 1 0 ... 0'

Thanks!

**Comment by tfzhou** [comment]
@halbielee Thanks for your interests to our work, as well as reporting these bugs. @Lixy1997 Could you please see the comments and fix them?

**Comment by Helens1997** [comment]
@halbielee  Thanks for your reporting these bugs, we have fixed them. As for the args.train_list, you can download the PASCAL VOC provided by us, and it contains the file.
