### ISSUE TITLE
img variable problem

### ISSUE THREAD

**Issue by ghost** [Lixy1997/Group-WSSS#6]
May I ask what is the img variable in train.py? 
It is on line 117 of the file train.py.
`losses.update(loss_train.data.item(), img.size()[0])`
I can't find the img variable before this.

Did you notice the file utils/imutils.py，on line 133 `class CenterCrop()` is missing a colon?

I look forward to your reply.

**Comment by tfzhou** [comment]
Hi @lesvay, thanks for reporting these bugs. For L117, I guess you could use ```img1.size()```; For L133, there is a miss of a colon symbol. We will fix these issues. Thanks!
